

# 七牛云
qiniu:
  #	Key
  ak: ### #自行去控制台看
  sk: ###
  # 存储空间名称
  bucket: ####
  # 存储空间下的目录
  dir: ###

# 清理指定目录下的md文件里面的垃圾图片
directory: ####

# 多少周期清理一次
#cleanCycle: 0 0 0 1 1/30 ? *
# 设置图片路径的正则表达式
urlRegex: http://*.com/.*png
